# Generated by Django 5.0.3 on 2024-03-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ruang milik jalan', 'ruang milik jalan'), ('lingkungan', 'lingkungan'), ('pelataran', 'pelataran'), ('gedung', 'gedung'), ('park and ride', 'park and ride'), ('vallet', 'vallet'), ('terminal parkir elektronik', 'terminal parkir elektronik')])),
            ],
        ),
        migrations.CreateModel(
            name='MekanismeTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mekanisme', to='tarif.jenistarif')),
            ],
        ),
        migrations.CreateModel(
            name='TarifParkir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MekanismeTarifGedung',
            fields=[
                ('mekanismetarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarif.mekanismetarif')),
            ],
            bases=('tarif.mekanismetarif',),
        ),
        migrations.CreateModel(
            name='MekanismeTarifLingkungan',
            fields=[
                ('mekanismetarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarif.mekanismetarif')),
            ],
            bases=('tarif.mekanismetarif',),
        ),
        migrations.CreateModel(
            name='MekanismeTarifParkAndRide',
            fields=[
                ('mekanismetarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarif.mekanismetarif')),
            ],
            bases=('tarif.mekanismetarif',),
        ),
        migrations.CreateModel(
            name='MekanismeTarifPelataran',
            fields=[
                ('mekanismetarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarif.mekanismetarif')),
            ],
            bases=('tarif.mekanismetarif',),
        ),
        migrations.CreateModel(
            name='MekanismeTarifRuangMilikJalan',
            fields=[
                ('mekanismetarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarif.mekanismetarif')),
                ('golongan', models.CharField(choices=[('jalan kawasan pengendalian parkir (KPP)', 'jalan kawasan pengendalian parkir (KPP)'), ('jalan A', 'jalan A'), ('jalan B', 'jalan B')])),
                ('jenis_kendaraan', models.CharField(choices=[('sedan', 'sedan'), ('jeep', 'jeep'), ('minibus', 'minibus'), ('pickup', 'pickup'), ('bus', 'bus'), ('truk', 'truk'), ('sepeda motor', 'sepeda motor'), ('sepeda', 'sepeda')])),
                ('min_tarif', models.IntegerField()),
                ('max_tarif', models.IntegerField()),
                ('cara_pembayaran', models.CharField(choices=[('per jam', 'per jam'), ('satu kali parkir', 'satu kali parkir')])),
            ],
            bases=('tarif.mekanismetarif',),
        ),
        migrations.CreateModel(
            name='MekanismeTarifTPE',
            fields=[
                ('mekanismetarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarif.mekanismetarif')),
            ],
            bases=('tarif.mekanismetarif',),
        ),
        migrations.CreateModel(
            name='MekanismeTarifVallet',
            fields=[
                ('mekanismetarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarif.mekanismetarif')),
            ],
            bases=('tarif.mekanismetarif',),
        ),
        migrations.AddField(
            model_name='jenistarif',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jenis', to='tarif.tarifparkir'),
        ),
    ]
