# Generated by Django 5.0.3 on 2024-03-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(choices=[('sedan', 'sedan'), ('jeep', 'jeep'), ('minibus', 'minibus'), ('pickup', 'pickup'), ('bus', 'bus'), ('truk', 'truk'), ('sepeda motor', 'sepeda motor'), ('sepeda', 'sepeda')])),
            ],
        ),
        migrations.AlterField(
            model_name='mekanismetarifruangmilikjalan',
            name='golongan',
            field=models.CharField(choices=[('jalan kawasan pengendalian parkir (KPP)', 'jalan kawasan pengendalian parkir (KPP)'), ('', 'jalan A'), ('jalan B', 'jalan B')]),
        ),
        migrations.RemoveField(
            model_name='mekanismetarifruangmilikjalan',
            name='jenis_kendaraan',
        ),
        migrations.AddField(
            model_name='mekanismetarifruangmilikjalan',
            name='jenis_kendaraan',
            field=models.ManyToManyField(to='tarif.kendaraan'),
        ),
    ]
