# Generated by Django 5.0.3 on 2024-03-08 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0002_kendaraan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MekanismeTarifHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_tarif_jam_pertama', models.IntegerField()),
                ('max_tarif_jam_pertama', models.IntegerField()),
                ('min_tarif_jam_berikutnya', models.IntegerField()),
                ('max_tarif_jam_berikutnya', models.IntegerField()),
                ('cara_pembayaran', models.CharField(choices=[('per jam', 'per jam'), ('satu kali parkir', 'satu kali parkir')])),
            ],
        ),
        migrations.CreateModel(
            name='MekanismeTarifLanggananKhusus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.IntegerField()),
                ('kali_parkir', models.IntegerField()),
                ('min_tarif_dasar', models.IntegerField()),
                ('max_tarif_dasar', models.IntegerField()),
                ('multiplier', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MekanismeTarifLanggananUmum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.IntegerField()),
                ('intensitas', models.IntegerField()),
                ('min_tarif_dasar', models.IntegerField()),
                ('max_tarif_dasar', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mekanismetarifgedung',
            name='jenis_kendaraan',
            field=models.ManyToManyField(to='tarif.kendaraan'),
        ),
        migrations.AddField(
            model_name='mekanismetariflingkungan',
            name='jenis_kendaraan',
            field=models.ManyToManyField(to='tarif.kendaraan'),
        ),
        migrations.AddField(
            model_name='mekanismetarifpelataran',
            name='jenis_kendaraan',
            field=models.ManyToManyField(to='tarif.kendaraan'),
        ),
        migrations.AddField(
            model_name='mekanismetarifgedung',
            name='mekanisme_harian',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='tarif.mekanismetarifharian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mekanismetariflingkungan',
            name='mekanisme_harian',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='tarif.mekanismetarifharian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mekanismetarifpelataran',
            name='mekanisme_harian',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='tarif.mekanismetarifharian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mekanismetarifgedung',
            name='mekanisme_langganan_khusus',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='tarif.mekanismetariflangganankhusus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mekanismetariflingkungan',
            name='mekanisme_langganan_khusus',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='tarif.mekanismetariflangganankhusus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mekanismetarifpelataran',
            name='mekanisme_langganan_khusus',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='tarif.mekanismetariflangganankhusus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mekanismetarifgedung',
            name='mekanisme_langganan_umum',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='tarif.mekanismetariflanggananumum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mekanismetariflingkungan',
            name='mekanisme_langganan_umum',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='tarif.mekanismetariflanggananumum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mekanismetarifpelataran',
            name='mekanisme_langganan_umum',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='tarif.mekanismetariflanggananumum'),
            preserve_default=False,
        ),
    ]
