# Generated by Django 5.0.3 on 2024-03-08 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0003_mekanismetarifharian_mekanismetariflangganankhusus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jenistarif',
            old_name='name',
            new_name='nama',
        ),
        migrations.AddField(
            model_name='mekanismetarifparkandride',
            name='cara_pembayaran',
            field=models.CharField(choices=[('per jam', 'per jam'), ('satu kali parkir', 'satu kali parkir'), ('per hari', 'per hari')], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mekanismetarifparkandride',
            name='jenis_kendaraan',
            field=models.ManyToManyField(to='tarif.kendaraan'),
        ),
        migrations.AddField(
            model_name='mekanismetarifparkandride',
            name='tarif',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mekanismetarifharian',
            name='cara_pembayaran',
            field=models.CharField(choices=[('per jam', 'per jam'), ('satu kali parkir', 'satu kali parkir'), ('per hari', 'per hari')]),
        ),
        migrations.AlterField(
            model_name='mekanismetarifruangmilikjalan',
            name='cara_pembayaran',
            field=models.CharField(choices=[('per jam', 'per jam'), ('satu kali parkir', 'satu kali parkir'), ('per hari', 'per hari')]),
        ),
        migrations.CreateModel(
            name='MekanismeTarifPenitipanKendaraan',
            fields=[
                ('mekanismetarif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarif.mekanismetarif')),
                ('tarif', models.IntegerField()),
                ('cara_pembayaran', models.CharField(choices=[('per jam', 'per jam'), ('satu kali parkir', 'satu kali parkir'), ('per hari', 'per hari')])),
                ('jenis_kendaraan', models.ManyToManyField(to='tarif.kendaraan')),
            ],
            bases=('tarif.mekanismetarif',),
        ),
    ]
