# Generated by Django 5.0.3 on 2024-03-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0004_rename_name_jenistarif_nama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mekanismetarifvallet',
            name='max_tarif',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mekanismetarifvallet',
            name='min_tarif',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
