# Generated by Django 5.0.3 on 2024-03-08 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0005_mekanismetarifvallet_max_tarif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisLanggananTPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam', models.IntegerField()),
                ('jenis_penggunaan_lahan_parkir', models.CharField(choices=[('menetap', 'menetap'), ('tidak menetap', 'tidak menetap')])),
            ],
        ),
        migrations.AddField(
            model_name='mekanismetariftpe',
            name='tarif_harian',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='tarif.jenistarif'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TarifLanggananTPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hari', models.IntegerField()),
                ('tarif_hari_jam', models.IntegerField()),
                ('jenis_kendaraan', models.ManyToManyField(to='tarif.kendaraan')),
                ('jenis_langganan_per_hari', models.ManyToManyField(related_name='tpe', to='tarif.jenislangganantpe')),
                ('tarif_tpe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarif_langganan', to='tarif.mekanismetariftpe')),
            ],
        ),
    ]
