# Generated by Django 5.0.3 on 2024-03-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0006_jenislangganantpe_mekanismetariftpe_tarif_harian_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenistarif',
            name='tarif',
        ),
        migrations.DeleteModel(
            name='TarifParkir',
        ),
    ]
