# Generated by Django 5.0.3 on 2024-03-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0007_remove_jenistarif_tarif_delete_tarifparkir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mekanismetarifruangmilikjalan',
            name='golongan',
            field=models.CharField(choices=[('jalan kawasan pengendalian parkir (KPP)', 'jalan kawasan pengendalian parkir (KPP)'), ('jalan A', 'jalan A'), ('jalan B', 'jalan B')]),
        ),
    ]
