# Generated by Django 5.0.3 on 2024-03-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LokasiParkir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_data', models.CharField(max_length=4)),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('ruang milik jalan', 'ruang milik jalan'), ('lingkungan', 'lingkungan'), ('pelataran', 'pelataran'), ('gedung', 'gedung'), ('park and ride', 'park and ride'), ('vallet', 'vallet'), ('terminal parkir elektronik', 'terminal parkir elektronik')])),
                ('alamat', models.CharField(max_length=100)),
                ('luas_m2', models.IntegerField()),
                ('kapasitas_mobil', models.IntegerField()),
                ('kapasitas_motor', models.IntegerField()),
                ('kapasitas_bus_truk', models.IntegerField()),
            ],
        ),
    ]
